print("hello")
print("hello world")
print("asd")
print("my name")
print("dog")
print("car")
print("house")
print("horse")
print("gamarjoba")
print("dog")
print("fruit")
print("apple")
print("animal")
print("goa")
print("python")
print("html")
print("css")
print("color")
print("black")
print("yellow")